### PR TITLE
Split mittsu gem into mittsu-core and mittsu-renderer-opengl

### LINKED ISSUE #115: Using mittsu without graphics
For my use case, I want to manipulate some 3d object files in Ruby, but I don't need to render them; instead I'm using THREE.js in the browser for that. So, in the interests of minimising dependencies would it be possible to make the library work without pulling in OpenGL unless a rendering context is created? I tried to use it without `glfw3` installed just to see if it would cope, but it wouldn't start up.

This could perhaps either be done by adapting the code in the library as-is, or for a more extreme solution, splitting the non-graphical stuff out into a separate gem, something like `mittsu-core`. Do you think either are possible? I'm happy to try this, but it would be good to know what approach you'd prefer I investigate before I do so!

### PR DESCRIPTION
**Pull request by Floppy**
This is an early PR for my attempt to resolve #115 by splitting mittsu into two gems. I think it can all be done in the same repo, and I've made it so that `mittsu` gem itself simply depends on the two component parts.

I've kept a single version string, and made them depend on that exact version, to avoid any differences causing problems. Can always be split later on. 

Resolves #115

### CODE REVIEW

**Comment by danini-the-panini** [comment]
Would we do this in subfolders, like Rails does?

**Comment by danini-the-panini** [comment]
Also is this a patch or minor version bump, since it doesn't really change the interface

**Comment by Floppy** [comment]
Yeah, subfolders is probably a good idea. And you right, technically by semver it would be a patch version, as absolutely nothing would change! Hah.

**Comment by Floppy** [comment]
Sorry, I never got much further on this. Hopefully I can come back to it soon.

**Comment by Floppy** [comment]
@danini-the-panini I think this is ready for you to take a look at. I've split it into separate folders rails-style, and there is a top-level `mittsu` gem for compatibility with existing installations, who shouldn't notice a difference. 

`gem build` appears to work for all 3 gemspecs, though how this would change your release process I leave up to you.

I'm having trouble running the examples (because of #130), so I can't actually *see* anything, but the tests seem good; although, I can't tell if coverage upload is still working.

**Comment by Floppy** [comment]
OK, after rebasing #131, the examples now run, which is great!

**Comment by danini-the-panini** [comment]
This is going to cause some nonsense now, since according to gem naming conventions, `mittsu-core` implicitely requires `mittsu/core` i.e. `Mittsu::Core` module, which is not desirable in this case since `Mittsu::Core` is only a subset of Mittsu's actual core functionality.

Considering Mittsu is pre-1.0, we can still reasonably introduce breaking changes in a minor version bump, and I think in this case it is warranted.

I'm going to split out the opengl renderer into its own gem and keep `mittsu` as a non-renderer 3d library. I think it makes sense to make it an extensible server-side analog to Three.js, with desktop-side rendering as a separate feature.

As for the opengl renderer, I'm going to move it to its own repo entirely.

**Comment by Floppy** [comment]
Makes sense to me!

**Comment by Floppy** [comment]
I think that's complete separation is a cleaner approach than what I've tried to do here with keeping compatibility and repo structure, so I'm 100% on board. Feel free to take anything useful from what I've done here, but also just throw it away if it's easier :)

**Pull request closed without merging**
