### PR TITLE
Test on Ruby 3.2 and 3.3

### PR DESCRIPTION
**Pull request by Floppy**

### CODE REVIEW

**Review by danini-the-panini — APPROVED** [review]

**Comment by Floppy** [comment]
The fails are because bundler isn't installing on Ruby 2.x versions. All of Ruby 2.x is very EOL now, so I could remove it and Mittsu goes Ruby 3 only? Or, if you want to keep supporting 2.x, we should find a way to get those builds working with an older version of bundler.

**Comment by danini-the-panini** [comment]
Could we just add the gem install bundler version to the workflow?

**Comment by Floppy** [comment]
Probably yes. I'll have a look.

**Comment by Floppy** [comment]
Having a go at fixing builds in #124

**Comment by Floppy** [comment]
#124 fixes the builds generally, so once that's merged in I'll update this one to go on top.

**Comment by Floppy** [comment]
All green! Side note, I love how fast these builds are now!

**Review by danini-the-panini — APPROVED** [review]

**Pull request merged**
